### ISSUE TITLE
Failing `start` command due to missing `google-protobuf` requirement

### ISSUE THREAD

**Issue by ColinCrawford** [architect-team/architect-cli#7]
```
Error: Error: Cannot find module 'google-protobuf'
    at Object.<anonymous> (~/Desktop/architect-io/calculator-example/addition-service/architect_services/addition_service/service_pb.js:10:12)
    at Object.error (/home/colin/Desktop/architect-io/architect-cli/node_modules/@oclif/errors/lib/index.js:22:17)
    at Start.error (/home/colin/Desktop/architect-io/architect-cli/node_modules/@oclif/command/lib/command.js:42:23)
    at Socket.cmd.stderr.on.data (/home/colin/Desktop/architect-io/architect-cli/src/commands/start.ts:134:16)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

**Comment by davidthor** [comment]
This ended up being due to a combination of failing install commands and issue https://github.com/architect-team/architect-cli/issues/9. This should be working now so long as you've closed the session after initial install. Closing this and will address session resets in the other issue.
